# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/repos/ECEN5863_HW/HW7_Practical/Vivado/counter/counter.cache/wt [current_project]
set_property parent.project_path E:/repos/ECEN5863_HW/HW7_Practical/Vivado/counter/counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/repos/ECEN5863_HW/HW7_Practical/Vivado/counter/counter.v
  E:/repos/ECEN5863_HW/HW7_Practical/Vivado/counter/counter_top.v
}
read_xdc E:/repos/ECEN5863_HW/HW7_Practical/Vivado/counter/counter.srcs/constrs_2/new/counter_top.xdc
set_property used_in_implementation false [get_files E:/repos/ECEN5863_HW/HW7_Practical/Vivado/counter/counter.srcs/constrs_2/new/counter_top.xdc]

synth_design -top counter_top -part xc7z020clg400-1
write_checkpoint -noxdef counter_top.dcp
catch { report_utilization -file counter_top_utilization_synth.rpt -pb counter_top_utilization_synth.pb }
