Implementation;Compile;RootName:CDC3FF
Implementation;Compile||(null)||Please refer to the log file for details||CDC3FF_compile_log.rpt;liberoaction://open_report/file/CDC3FF_compile_log.rpt||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98304003||Info: I/O Bank Assigner detected (1) out of (6) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:CDC3FF
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||CDC3FF_placeroute_log.rpt;liberoaction://open_report/file/CDC3FF_placeroute_log.rpt||(null);(null)
HelpInfo,E:\Microsemi\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,E:\Microsemi\SynplifyPro\bin\mbin\assistant
