Implementation;Compile;RootName:top_level_model
Implementation;Compile||(null)||Please refer to the log file for details||top_level_model_compile_log.rpt;liberoaction://open_report/file/top_level_model_compile_log.rpt||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/79299167||Info: Combinational loops have been detected in the design. To view the details, go to Tools->Reports->Timing->Combinational_Loops||(null);(null)||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98304003||Info: I/O Bank Assigner detected (1) out of (6) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:top_level_model
Implementation;Place and Route||(null)||Please refer to the log file for details about 4 Info(s)||top_level_model_placeroute_log.rpt;liberoaction://open_report/file/top_level_model_placeroute_log.rpt||(null);(null)
HelpInfo,E:\Microsemi\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,E:\Microsemi\SynplifyPro\bin\mbin\assistant
